### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#1]
```
http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/Volumes/big/atelier_carto/PROJECTS/WAEND/app/waend/node_modules/express/lib/response.js:564:10)
    at ServerResponse.json (/Volumes/big/atelier_carto/PROJECTS/WAEND/app/waend/node_modules/express/lib/response.js:208:10)
    at ServerResponse.send (/Volumes/big/atelier_carto/PROJECTS/WAEND/app/waend/node_modules/express/lib/response.js:116:21)
    at success (/Volumes/big/atelier_carto/PROJECTS/WAEND/app/waend/routes/media.js:125:18)
    at Object.oncomplete (fs.js:107:15)
```

**Comment by pierremarc** [comment]
you might want to check your config though
